help: ##Print this message
	@fgrep -h "##" $(MAKEFILE_LIST) | fgrep -v fgrep | sed -e 's/\\$$//' | sed -e 's/##//'
frontend: ## Install Frontend Component
	@echo installing frontend
cart: ## Install cart Component
	@echo installing cart
catalogue: ## Install Catalogue Component
	@echo intalling Catalogue
mongodb: ## Install MongoDB Component
	@echo intalling MongoDB
mysql: ## Install MYSQL Component
	@echo installing MYSQL
payment: ## Install Payment Component
	@echo installing Payment
rabbitmq: ## Install RabbitMQ Component
	@echo installing Rabbitmq
redis: ## Install Redis Component
	@echo installing Redis
shipping: ## Install Shipping Component
	@echo intalling Shipping