frontend:
	@echo installing frontend
cart:
	@echo installing cart
catalogue:
	@echo intalling Catalogue
mongodb:
	@echo intalling mongodb
mysql:
	@echo installing mysql
payment:
	@echo installing payment
rabbitmq:
	@echo installing rabbitmq
redis:
	@echo installing redis
shipping:
	@echo intalling shipping